RoundTime: 180
DifficultyMin: 1
DifficultyMax: 10
BlockCountMin: 70
BlockCountMax: 100
StopTimeMin: 12
StopTimeMax: 8
Cycle: 3
canBuilderPlacePoint1: {}
canBuilderPlacePoint2: {}
BuilderSpawnPoint:
  world: world
  x: 0
  y: 0
  z: 0
  yaw: 0
  pitch: 0
DuplicateTheme: false
ShowDifficulty: true
ShowGenre: true
AllowAllGenre: true
Debug: false
AllowGenre:
  - "未設定"
