name: NGBuilder
version: ${project.version}
main: io.github.axtuki1.ngbuilder.NGBuilder
api-version: 1.14
permissions:
  Builder.GameMaster:
    default: op
  Builder.Player:
    default: true
  Builder.Broadcaster:
    default: false
commands:
  builder:
    permission: Builder.Player
  clean:
    permission: Builder.Player