name: NGBuilder
version: ${project.version}
main: io.github.axtuki1.ngbuilder.NGBuilder
permissions:
  Builder.GameMaster:
    default: op
  Builder.Player:
    default: true
commands:
  builder:
    permission: Builder.Player
  clean:
    permission: Builder.Player